### ISSUE TITLE
3D print stencil cutouts

### ISSUE THREAD

**Issue by HarunKilic** [S-March/smarchWatch_PUBLIC#33]
Hi, nice project! 

Is it possible to 3d print stencil cutouts?

**Comment by S-March** [comment]
I'm afraid the pads for the microcontroller will be too small for a normal printer to get right (resolution wise). Additionally, you would like to keep the thickness tolerance of your stencil extremely tight so that you don't over/under apply paste. Services like OSHStencil can get you an excellent stainless steel stencil for very cheap.
